using OpenScribe.Core.Enums;

namespace OpenScribe.Core.Models;

/// <summary>
/// A single step in a documented process — one click/action by the user.
/// </summary>
public class ProcessStep
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid SessionId { get; set; }

    /// <summary>1-based ordering of this step within the session.</summary>
    public int SequenceNumber { get; set; }

    /// <summary>Timestamp relative to session start.</summary>
    public TimeSpan Timestamp { get; set; }

    // ── Click data ───────────────────────────────────────────────
    public int ClickX { get; set; }
    public int ClickY { get; set; }
    public ClickType ClickType { get; set; }

    /// <summary>Title of the window that was focused at click time.</summary>
    public string WindowTitle { get; set; } = string.Empty;

    /// <summary>Name/AutomationId of the UI control that was clicked.</summary>
    public string? ControlName { get; set; }

    /// <summary>The application (process name) that owned the focused window.</summary>
    public string? ApplicationName { get; set; }

    // ── UI Automation metadata ──────────────────────────────────
    /// <summary>UIA control type (e.g., "Button", "TextBox").</summary>
    public string? UiaControlType { get; set; }

    /// <summary>UIA element name (visible label).</summary>
    public string? UiaElementName { get; set; }

    /// <summary>UIA automation ID.</summary>
    public string? UiaAutomationId { get; set; }

    /// <summary>UIA class name.</summary>
    public string? UiaClassName { get; set; }

    /// <summary>UIA element bounding rectangle as JSON.</summary>
    public string? UiaElementBounds { get; set; }

    /// <summary>DPI scale factor at capture time.</summary>
    public double DpiScale { get; set; } = 1.0;

    // ── Screenshot data ──────────────────────────────────────────
    /// <summary>Path to the full-resolution screenshot PNG.</summary>
    public string ScreenshotPath { get; set; } = string.Empty;

    /// <summary>Path to a cropped region around the click area.</summary>
    public string? CroppedScreenshotPath { get; set; }

    /// <summary>Path to the annotated screenshot (with red box/arrow/badge).</summary>
    public string? AnnotatedScreenshotPath { get; set; }

    /// <summary>Path to the cropped+annotated detail screenshot (zoomed in on the highlight).</summary>
    public string? DetailScreenshotPath { get; set; }

    // ── Keyboard input ─────────────────────────────────────────────
    /// <summary>Accumulated text typed during or before this step (e.g., "ls -la[Enter]").</summary>
    public string? TypedText { get; set; }

    /// <summary>Number of keystrokes that produced the typed text.</summary>
    public int KeystrokeCount { get; set; }

    // ── OCR & transcription ──────────────────────────────────────
    /// <summary>OCR text extracted from the click region.</summary>
    public string? OcrText { get; set; }

    /// <summary>Voice narration transcript for the time range of this step.</summary>
    public string? VoiceTranscript { get; set; }

    // ── AI-generated content ─────────────────────────────────────
    /// <summary>Short title generated by AI (e.g., "Click the Submit button").</summary>
    public string? AiGeneratedTitle { get; set; }

    /// <summary>Full instruction text generated by AI.</summary>
    public string? AiGeneratedInstruction { get; set; }

    /// <summary>Optional notes/tips generated by AI.</summary>
    public string? AiGeneratedNotes { get; set; }

    /// <summary>Highlight region suggested by AI for annotation (JSON rect).</summary>
    public string? AiHighlightRegion { get; set; }

    /// <summary>Crop region suggested by AI for detail view (JSON rect). Separate from highlight.</summary>
    public string? AiCropRegion { get; set; }

    // ── User overrides ───────────────────────────────────────────
    /// <summary>User-edited instruction (overrides AI if set).</summary>
    public string? UserEditedInstruction { get; set; }

    /// <summary>User-added notes.</summary>
    public string? UserNotes { get; set; }

    /// <summary>Whether the user excluded this step from the final document.</summary>
    public bool IsExcluded { get; set; }

    // ── Computed ─────────────────────────────────────────────────
    /// <summary>Returns the effective instruction text (user edit takes priority).</summary>
    public string EffectiveInstruction =>
        !string.IsNullOrWhiteSpace(UserEditedInstruction)
            ? UserEditedInstruction
            : AiGeneratedInstruction ?? string.Empty;
}
